---
#--------------------------------------------------------------------
# paramètres commun
# dans cette section ne rien modifier sauf si besoin
#--------------------------------------------------------------------

oracle_home: "/u01/app/oracle/product/19.0.0/dbhome_1"
dbvisit_home: "/usr/dbvisit"