---
  #-------------------------------------------
  # configuration des mes VMs et serveurs
  #-------------------------------------------

  #-------------------------------------------
  # installation de telegraf
  #-------------------------------------------

#  - name: get id 
#    shell: cat /etc/os-release | grep "^ID=" | cut -d= -f2
#    register: os_id

  - name: get version_codename 
    shell: cat /etc/os-release | grep "VERSION_CODENAME=" | cut -d= -f2
    register: version_codename

  #-------------------------------------------
  # Debian : installation de telegraf
  #-------------------------------------------
  - name: download influxdb key
    get_url: url=https://repos.influxdata.com/influxdb.key dest=/etc/apt/trusted.gpg.d/influxdb.asc
    when: ansible_os_family == 'Debian'

  - name: remove repo file for debian
    file: 
      path: /etc/apt/sources.list.d/influxdb.list
      state: absent
    when: ansible_os_family == 'Debian'

  - name: create repo file for debian
    lineinfile: 
      dest: /etc/apt/sources.list.d/influxdb.list
      line: "deb https://repos.influxdata.com/debian {{version_codename.stdout}} stable"
      create: yes
    when: ansible_os_family == 'Debian'


  - name: install telgreaf
    apt: name=telegraf state=present
    when: ansible_os_family == 'Debian'

  #-------------------------------------------
  # RedHat : installation de telegraf
  #-------------------------------------------
  - name: create repo file for RedHat
    file: src=influxdb.repo dest=/etc/yum.repos.d/influxdb.repo owner=root group=root mode=0755 
    when: ansible_os_family == 'RedHat'

  - name: install telgreaf
    yum: name=telegraf state=present 
    when: ansible_os_family == 'RedHat'

  - name: create config file
    copy: src=telegraf.conf dest=/etc/telegraf/telegraf.conf owner=root group=root mode=0755

  - name: delete log file if exist
    file: path=/var/log/telegraf.log state=absent

  - name: create new log file 
    file: path=/var/log/telegraf.log state=touch owner=telegraf group=telegraf mode=0755

  - name: restart tlegraf
    service: name=telegraf state=restarted

