---
  #-------------------------------------------
  # configuration des mes VMs et serveurs
  #-------------------------------------------

  #-------------------------------------------
  # installation de telegraf
  #-------------------------------------------

  - name: download influxdb key
    get_url: url=https://repos.influxdata.com/influxdb.key dest=/etc/apt/trusted.gpg.d/influxdb.asc

  - name: get id 
    shell: cat /etc/os-release | grep "^ID=" | cut -d= -f2
    register: os_id

  - name: get version_codename 
    shell: cat /etc/os-release | grep "VERSION_CODENAME=" | cut -d= -f2
    register: version_codename

  - name: remove repo file for debian
    file: 
      path: /etc/apt/sources.list.d/influxdb.list
      state: absent
    when: ansible_os_family == 'Debian'

  - name: create repo file for debian
    lineinfile: 
      dest: /etc/apt/sources.list.d/influxdb.list
      line: "deb https://repos.influxdata.com/{{os_id.stdout}} {{version_codename.stdout}} stable"
      create: yes
    when: ansible_os_family == 'Debian'

  - name: delete log file if exist
    file: path=/var/log/telegraf.log state=absent

  - name: create new log file 
    file: path=/var/log/telegraf.log present=absent owner=telegraf group=telegraf mode=0755

  - name: install telgreaf
    apt: name=telegraf state=present
    when: ansible_os_family == 'Debian'

  - name: create repo file for Redhat
    blockinfile:
      path: /etc/yum.repos.d/influxdb.repo
      block: |
        [influxdb]
        name = InfluxDB Repository - RHEL $releasever
        baseurl = https://repos.influxdata.com/rhel/$releasever/$basearch/stable
        enabled = 1
        gpgcheck = 1
        gpgkey = https://repos.influxdata.com/influxdb.key
    when: ansible_os_family == 'Redhat'

  - name: install telgreaf
    yum: name=telegraf state=present 
    when: ansible_os_family == 'Redhat'

  - name: create config file
    copy: src=telegraf.conf dest=/etc/telegraf/telegraf.conf owner=root group=root mode=0755

  - name: restart tlegraf
    service: name=telegraf state=restarted

