---
  # --------------------------------------------------- 
  # configuration réseau
  # ---------------------------------------------------
  - name: Modification resolv.conf pour ajouter attempts et timeout
    lineinfile: dest=/etc/resolv.conf line="{{ item.line }}"
    with_items:
     - { line: "options attempts:2" }
     - { line: "options timeout:1" }
  
  - name: Desactivation de IP v6 et ZeroConf (Doc ID 1161144.1)
    lineinfile: dest=/etc/sysconfig/network line="{{ item.line }}"
    with_items:
     - { line: "NETWORKING_IPV6=no" }
     - { line: "IPV6INIT=no" }
     - { line: "NOZEROCONF=yes" }
    tags: ipv6

  - name: desactivation permanente de IP v6
    lineinfile: 
      dest=/etc/modprobe.d/desactivation_ipv6.conf 
      line="options ipv6 disable=1" 
      state=present
      create=yes
