# Fichier de paramètres pour Oracle Linux 8
---

  #----------------------------------------------------------------------
  # packages linux nécessaires pour travailler
  #----------------------------------------------------------------------
  linux_packages:
       - bc
       - binutils
       - elfutils-libelf
       - elfutils-libelf-devel
       - fontconfig-devel
       - glibc
       - glibc-devel
       - ksh
       - libaio
       - libaio-devel
       - libgcc
       - libibverbs
       - libnsl
       - librdmacm
       - libstdc++
       - libstdc++-devel
       - libX11
       - libXau
       - libxcb
       - libXi
       - libXrender
       - libXtst
       - make
       - net-tools
       - nfs-utils
       - policycoreutils
       - policycoreutils-python-utils
       - smartmontools
       - sysstat
       - unixODBC
       - chrony
       - vim
       - vim-enhanced

