---
#--------------------------------------------------------------------
# paramètres commun
# dans cette section ne rien modifier sauf si besoin
#--------------------------------------------------------------------

scripts_dir: "/home/oracle/scripts"
