---
  # --------------------------------------------------- 
  # configuration Linux : grub pour Linux 8
  # ---------------------------------------------------

  # ---------------------------------------------------
  # suppression de rhgb
  # ---------------------------------------------------
  - name: check if rhgb is set 
    ansible.builtin.shell: grubby --info DEFAULT | grep rhgb | wc -l
    register: rhgb_count

  - name: Configuration grub Linux 7/8 - Suppression de rhgb
    shell: grubby --update-kernel=ALL --remove-args=rhgb 
    when: rhgb_count.stdout != 0
    when: ansible_distribution_major_version >= '7'
    tags: grub

  # ---------------------------------------------------
  # suppression de quiet
  # ---------------------------------------------------
  - name: check if quiet is set 
    ansible.builtin.shell: grubby --info DEFAULT | grep quiet | wc -l
    register: quiet_count

  - name: Configuration grub Linux 7/8 - Suppression de quiet
    shell: grubby --update-kernel=ALL --remove-args=quiet 
    when: rhgb_count.stdout != 0
    when: ansible_distribution_major_version >= '7'
    tags: grub

#  - name: Configuration grub Linux 7/8 - Suppression de quiet et rhgb
#    shell: grubby --update-kernel=ALL --remove-args=rhgb 
#    with_items:
#        - "rhgb"
#        - "quiet"
#    when: ansible_distribution_major_version >= '7'
#    tags: grub

  - name: Configuration grub Linux 7/8 -  Désactivation de Transparent Hugepages, numa et deadline
    shell: grubby --update-kernel=ALL --args={{ item }} 
    with_items:
        - "transparent_hugepage=never"
        - "numa=off"
        - "elevator=deadline"
        - "vga=791"
        #  Workaround of Orabug 20734786
        - "GRUB_ENABLE_BLSCFG=true"
    when: ansible_distribution_major_version >= '7'
    tags: grub


