---
  # --------------------------------------------------- 
  # configuration Linux : grub pour Linux 8
  # ---------------------------------------------------
  - name: Configuration grub Linux 7/8 - Suppression de quiet et rhgb
    shell: grubby --update-kernel=ALL --remove-args={{ item }} 
    with_items:
        - "rhgb"
        - "quiet"
    when: ansible_distribution_major_version >= '7'
    tags: grub

  - name: Configuration grub Linux 7/8 -  Désactivation de Transparent Hugepages, numa et deadline
    shell: grubby --update-kernel=ALL --args={{ item }} 
    with_items:
        - "transparent_hugepage=never"
        - "numa=off"
        - "elevator=deadline"
        - "vga=791"
        #  Workaround of Orabug 20734786
        - "GRUB_ENABLE_BLSCFG=true"
    when: ansible_distribution_major_version >= '7'
    tags: grub


