---
# 
# installation des binaires ORACLE et patch
#

# installation des binaires Oracle DB
  - include: install_database.yml

# Application du patch
  - include: opatch_apply.yml

# Ajout des sripts d'exploitation
  - include: scripts_exploitation.yml

