---
- hosts: all
  remote_user: oracle

  vars:
    u01_size_gb: 1
    tmp_size_gb: 1
    patch_dir: "{{ oracle_sources }}"
    opatch_file: p6880880_190000_Linux-x86-64.zip
    psu_file: p34133642_190000_Linux-x86-64_RU_19.16.zip
    patch_number: 34133642

  tasks:
  - name: Vérification de l'espace disque u01
    action: shell df -P /u01 | awk 'END { print $4 }'
    register: u01size
    failed_when: u01size.stdout|int < {{ u01_size_gb }} * 1024 * 1024

  - name: Vérification de l'espace disque tmp
    action: shell df -P /tmp | awk 'END { print $4 }'
    register: tmpsize
    failed_when: tmpsize.stdout|int < {{ tmp_size_gb }} * 1024 * 1024

  - name: Installation OPatch dns ORACLE_HOME
    action: shell unzip -oq {{ patch_dir }}/{{ opatch_file }} -d {{ oracle_home }}

  - name: unzip du patch
    action: shell unzip -oq {{ patch_dir }}/{{ psu_file }} -d {{ patch_dir }}

  - name: patch conflict detection
    action: shell export ORACLE_HOME={{ oracle_home }}; cd {{ patch_remote_dir }}/{{ patch_number }}; $ORACLE_HOME/OPatch/opatch prereq CheckConflictAgainstOHWithDetail -ph ./
    register: conflict_detection
    failed_when: "'Prereq \"checkConflictAgainstOHWithDetail\" passed.' not in conflict_detection.stdout"

  - name: Application du patch 
    action: shell export ORACLE_HOME={{ oracle_home}}; cd {{ patch_dir }}/{{ patch_number }}; $ORACLE_HOME/OPatch/opatch apply -silent
    register: apply_psu
    failed_when: "'OPatch succeeded.' not in apply_psu.stdout"

  - name: Résultat de l'installation via OPatch
    shell: "{{ oracle_home }}/OPatch/opatch lsinventory"
    become: true
    become_method: su
    become_user: oracle
    register: opatchls
    tags: opatch

  - debug: var=opatchls.stdout_lines
    # with_items: opatchls.results
    tags: opatch

  - name: Nettoyage du répertoire du patch
    file: path={{ patch_number }} state=absent

